import { Language } from './types.ts';

interface TranslationSet {
  // StartMenu
  title: string;
  subtitle: string;
  description: string;
  beginJourney: string;
  selectLanguage: string;
  narrativeModeLabel: string;
  narrativeModeComplete: string;
  narrativeModeSummary: string;
  enableImageGeneration: string;
  load_game: string;
  shop_button: string;
  library_button: string;
  
  // Intro
  intro_prologue: string[];
  intro_continue: string;

  // Tutorial
  tutorial_title: string;
  tutorial_welcome_title: string;
  tutorial_welcome_desc: string;
  tutorial_keywords_title: string;
  tutorial_keywords_desc: string;
  tutorial_choices_title: string;
  tutorial_choices_desc: string;
  tutorial_combat_title: string;
  tutorial_combat_desc: string;
  tutorial_status_title: string;
  tutorial_status_desc: string;
  tutorial_begin_adventure: string;

  // World Briefing
  briefing_title: string;
  briefing_world_name: string;
  briefing_difficulty: string;
  briefing_begin: string;

  // Shop
  shop_title: string;
  shop_back_to_menu: string;
  shop_your_echoes: string;
  shop_item_hp_name: string;
  shop_item_hp_desc: string;
  shop_item_potion_name: string;
  shop_item_potion_desc: string;
  shop_buy_button: string;
  shop_max_level: string;

  // Game Header & Status
  save_game: string;
  game_saved: string;
  status_button: string;
  status_title: string;
  hp: string;
  attributes: string;
  inventory: string;
  party: string;
  moves: string;

  // Scenario Prompts (internal)
  scenario_king_prompt: string;
  scenario_church_prompt: string;
  scenario_mages_prompt: string;
  scenario_ancestral_prompt: string;

  // Game
  summoningWorld: string;
  writingDestiny: string;
  generating_image: string;
  imageDisclaimer: string;
  loadError: string;

  // GameOverScreen
  endOfTale: string;
  playAgain: string;
  echoes_earned: string; // {count}
  run_summary: string; // {turns}, {difficulty}
  
  // Gemini Service Errors
  errorParse: string;
  errorConnection: string;

  // Character Creation
  character_creation_title: string;
  character_creation_sex: string;
  character_creation_male: string;
  character_creation_female: string;
  character_creation_age: string;
  age_young_adult: string;
  age_adult: string;
  age_middle_aged: string;
  age_elder: string;
  character_creation_personality: string;
  personality_stoic: string;
  personality_jovial: string;
  personality_cynical: string;
  personality_brave: string;
  personality_scholarly: string;
  character_creation_skin_tone: string;
  character_creation_hair_style: string;
  hair_style_short_messy: string;
  hair_style_long_straight: string;
  hair_style_braided: string;
  hair_style_top_knot: string;
  hair_style_curly_wild: string;
  hair_style_bald: string;
  hair_style_ponytail: string;
  hair_style_undercut: string;
  hair_style_buzz_cut: string;
  hair_style_wavy_bob: string;
  character_creation_hair_color: string;
  character_creation_eye_color: string;
  character_creation_regenerate: string;
  character_creation_generating: string;
  character_creation_cooldown: string;
  character_creation_begin_journey: string;
  character_creation_error: string;
  character_creation_error_generic: string;
  
  // Journey Library
  library_title: string;
  library_back_to_menu: string;
  library_no_journeys: string;
  library_journey_date: string;
  library_journey_world: string;
  library_journey_turns: string;
  library_journey_difficulty: string;
  library_view_button: string;
  library_delete_button: string;
  library_export_button: string;
  library_delete_confirm: string;
  library_final_outcome: string;
  library_character: string;
  library_story_log: string;
  library_save_journey: string;
  library_journey_saved: string;
}

export const translations: Record<Language, TranslationSet> = {
  en: {
    title: "Earth of Dungeons",
    subtitle: "A Summoner's Story",
    description: "Explore the World of magic",
    beginJourney: "Enter",
    selectLanguage: "Language:",
    narrativeModeLabel: "Narrative Style:",
    narrativeModeComplete: "Complete",
    narrativeModeSummary: "Summary",
    enableImageGeneration: "Enable Image Generation",
    load_game: "Load Game",
    shop_button: "Shop",
    library_button: "Journey Library",
    
    intro_prologue: [
      "In a world not your own...",
      "Summoned by a desperate plea...",
      "Your story is about to begin."
    ],
    intro_continue: "Continue",

    tutorial_title: "How to Play",
    tutorial_welcome_title: "Welcome, Summoned One",
    tutorial_welcome_desc: "This is a world shaped by your decisions. The story is generated by an AI Dungeon Master, making every playthrough unique.",
    tutorial_keywords_title: "Interactive World",
    tutorial_keywords_desc: "You'll find <span class='text-amber-400 font-bold'>highlighted keywords</span> in the text. Click on them to learn more about the world, its characters, and your own abilities.",
    tutorial_choices_title: "Make Your Choice",
    tutorial_choices_desc: "Choose from the buttons below the story to act. Sometimes, you may even be asked to type your own response. Choose wisely.",
    tutorial_combat_title: "Turn-Based Combat",
    tutorial_combat_desc: "When you encounter an enemy, the game will shift to a combat screen. Select one of your 4 combat moves to attack, and the AI will describe the outcome.",
    tutorial_status_title: "Track Your Hero",
    tutorial_status_desc: "At the top of the screen, you can check your Status to see your attributes, HP, inventory, and combat moves at any time.",
    tutorial_begin_adventure: "Begin Your Adventure",

    briefing_title: "World Briefing",
    briefing_world_name: "World Name:",
    briefing_difficulty: "Difficulty:",
    briefing_begin: "Enter this World",

    shop_title: "Echoes Shop",
    shop_back_to_menu: "Back to Menu",
    shop_your_echoes: "Your Echoes:",
    shop_item_hp_name: "Vitality Boost",
    shop_item_hp_desc: "Permanently increase your starting HP.",
    shop_item_potion_name: "Starting Potion",
    shop_item_potion_desc: "Begin each new journey with a Health Potion in your inventory.",
    shop_buy_button: "Buy for {cost}",
    shop_max_level: "Max Level",

    save_game: "Save Game",
    game_saved: "Game Saved!",
    status_button: "Status",
    status_title: "Player Status",
    hp: "HP",
    attributes: "Attributes",
    inventory: "Inventory",
    party: "Party",
    moves: "Combat Moves",

    scenario_king_prompt: "The player is summoned by a desperate king to save his besieged kingdom.",
    scenario_church_prompt: "The player is summoned by the high church, who believe them to be a prophesied hero.",
    scenario_mages_prompt: "The player is summoned by a cabal of rogue mages for their own mysterious purposes.",
    scenario_ancestral_prompt: "The player is summoned by a last-resort ancestral magic as an ancient evil reawakens.",

    summoningWorld: "Summoning a new world...",
    writingDestiny: "Destiny is being written...",
    generating_image: "A vision is forming...",
    imageDisclaimer: "Image is an artistic interpretation of the scene.",
    loadError: "Failed to load the story. Please try refreshing.",
    endOfTale: "The End of the Tale",
    playAgain: "Play Again",
    echoes_earned: "You gathered {count} Echoes.",
    run_summary: "{turns} survived in a world of difficulty {difficulty}/10.",
    
    errorParse: "Could not parse the story continuation. The thread of fate is tangled.",
    errorConnection: "The connection to the ethereal plane was lost.",
    
    character_creation_title: "Create Your Hero",
    character_creation_sex: "Sex",
    character_creation_male: "Male",
    character_creation_female: "Female",
    character_creation_age: "Age",
    age_young_adult: "Young Adult (18-25)",
    age_adult: "Adult (26-40)",
    age_middle_aged: "Middle-aged (41-60)",
    age_elder: "Elder (60+)",
    character_creation_personality: "Personality",
    personality_stoic: "Stoic",
    personality_jovial: "Jovial",
    personality_cynical: "Cynical",
    personality_brave: "Brave",
    personality_scholarly: "Scholarly",
    character_creation_skin_tone: "Skin Tone",
    character_creation_hair_style: "Hair Style",
    hair_style_short_messy: "Short and messy",
    hair_style_long_straight: "Long and straight",
    hair_style_braided: "Braided",
    hair_style_top_knot: "Top-knot",
    hair_style_curly_wild: "Curly and wild",
    hair_style_bald: "Bald",
    hair_style_ponytail: "Ponytail",
    hair_style_undercut: "Undercut",
    hair_style_buzz_cut: "Buzz Cut",
    hair_style_wavy_bob: "Wavy Bob",
    character_creation_hair_color: "Hair Color",
    character_creation_eye_color: "Eye Color",
    character_creation_regenerate: "Regenerate Portrait",
    character_creation_generating: "Generating...",
    character_creation_cooldown: "On Cooldown...",
    character_creation_begin_journey: "Begin Journey",
    character_creation_error: "Failed to generate portrait. Please try again.",
    character_creation_error_generic: "An error occurred while generating the portrait.",
    
    library_title: "Journey Library",
    library_back_to_menu: "Back to Menu",
    library_no_journeys: "Your library is empty. Complete a journey to save it here.",
    library_journey_date: "Date",
    library_journey_world: "World",
    library_journey_turns: "Turns",
    library_journey_difficulty: "Difficulty",
    library_view_button: "View",
    library_delete_button: "Delete",
    library_export_button: "Export to File",
    library_delete_confirm: "Are you sure you want to delete this journey forever?",
    library_final_outcome: "Final Outcome",
    library_character: "Character",
    library_story_log: "Story Log",
    library_save_journey: "Save Journey to Library",
    library_journey_saved: "Journey Saved!",
  },
  pt: {
    title: "Earth of Dungeons",
    subtitle: "A História de um Invocado",
    description: "Explore o Mundo de magia",
    beginJourney: "Entrar",
    selectLanguage: "Idioma:",
    narrativeModeLabel: "Estilo da Narrativa:",
    narrativeModeComplete: "Completo",
    narrativeModeSummary: "Resumido",
    enableImageGeneration: "Habilitar Geração de Imagem",
    load_game: "Carregar Jogo",
    shop_button: "Loja",
    library_button: "Biblioteca de Jornadas",
    
    intro_prologue: [
      "Em um mundo que não é o seu...",
      "Invocado por um apelo desesperado...",
      "Sua história está prestes a começar."
    ],
    intro_continue: "Continuar",

    tutorial_title: "Como Jogar",
    tutorial_welcome_title: "Bem-vindo, Invocado",
    tutorial_welcome_desc: "Este é um mundo moldado por suas decisões. A história é gerada por um Mestre de Jogo de IA, tornando cada partida única.",
    tutorial_keywords_title: "Mundo Interativo",
    tutorial_keywords_desc: "Você encontrará <span class='text-amber-400 font-bold'>palavras-chave destacadas</span> no texto. Clique nelas para saber mais sobre o mundo, seus personagens e suas próprias habilidades.",
    tutorial_choices_title: "Faça sua Escolha",
    tutorial_choices_desc: "Escolha uma das opções abaixo da história para agir. Às vezes, você pode até ser solicitado a digitar sua própria resposta. Escolha com sabedoria.",
    tutorial_combat_title: "Combate por Turnos",
    tutorial_combat_desc: "Quando encontrar um inimigo, o jogo mudará para uma tela de combate. Selecione um dos seus 4 movimentos de combate para atacar, e a IA descreverá o resultado.",
    tutorial_status_title: "Acompanhe seu Herói",
    tutorial_status_desc: "No topo da tela, você pode verificar seu Status para ver seus atributos, HP, inventário e movimentos de combate a qualquer momento.",
    tutorial_begin_adventure: "Comece sua Aventura",

    briefing_title: "Relatório do Mundo",
    briefing_world_name: "Nome do Mundo:",
    briefing_difficulty: "Dificuldade:",
    briefing_begin: "Entrar neste Mundo",

    shop_title: "Loja de Ecos",
    shop_back_to_menu: "Voltar ao Menu",
    shop_your_echoes: "Seus Ecos:",
    shop_item_hp_name: "Aumento de Vitalidade",
    shop_item_hp_desc: "Aumenta permanentemente seu HP inicial.",
    shop_item_potion_name: "Poção Inicial",
    shop_item_potion_desc: "Comece cada nova jornada com uma Poção de Vida em seu inventário.",
    shop_buy_button: "Comprar por {cost}",
    shop_max_level: "Nível Máximo",

    save_game: "Salvar Jogo",
    game_saved: "Jogo Salvo!",
    status_button: "Status",
    status_title: "Status do Jogador",
    hp: "HP",
    attributes: "Atributos",
    inventory: "Inventário",
    party: "Grupo",
    moves: "Movimentos de Combate",

    scenario_king_prompt: "O jogador é invocado por um rei desesperado para salvar seu reino sitiado.",
    scenario_church_prompt: "O jogador é invocado pela alta igreja, que acredita que ele seja um herói profetizado.",
    scenario_mages_prompt: "O jogador é invocado por um conluio de magos renegados para seus próprios propósitos misteriosos.",
    scenario_ancestral_prompt: "O jogador é invocado por uma magia ancestral de último recurso enquanto um mal antigo redesperta.",

    summoningWorld: "Invocando um novo mundo...",
    writingDestiny: "O destino está sendo escrito...",
    generating_image: "Uma visão está se formando...",
    imageDisclaimer: "A imagem é uma interpretação artística da cena.",
    loadError: "Falha ao carregar a história. Por favor, tente atualizar.",
    endOfTale: "O Fim da História",
    playAgain: "Jogar Novamente",
    echoes_earned: "Você coletou {count} Ecos.",
    run_summary: "{turns} turnos sobrevividos em um mundo de dificuldade {difficulty}/10.",

    errorParse: "Não foi possível analisar a continuação da história. O fio do destino está emaranhado.",
    errorConnection: "A conexão com o plano etéreo foi perdida.",

    character_creation_title: "Crie seu Herói",
    character_creation_sex: "Sexo",
    character_creation_male: "Masculino",
    character_creation_female: "Feminino",
    character_creation_age: "Idade",
    age_young_adult: "Jovem Adulto (18-25)",
    age_adult: "Adulto (26-40)",
    age_middle_aged: "Meia-idade (41-60)",
    age_elder: "Idoso (60+)",
    character_creation_personality: "Personalidade",
    personality_stoic: "Estóico",
    personality_jovial: "Jovial",
    personality_cynical: "Cínico",
    personality_brave: "Corajoso",
    personality_scholarly: "Erudito",
    character_creation_skin_tone: "Tom de Pele",
    character_creation_hair_style: "Estilo de Cabelo",
    hair_style_short_messy: "Curto e bagunçado",
    hair_style_long_straight: "Longo e liso",
    hair_style_braided: "Trançado",
    hair_style_top_knot: "Coque alto",
    hair_style_curly_wild: "Cacheado e selvagem",
    hair_style_bald: "Calvo",
    hair_style_ponytail: "Rabo de Cavalo",
    hair_style_undercut: "Undercut",
    hair_style_buzz_cut: "Corte Raspado",
    hair_style_wavy_bob: "Bob Ondulado",
    character_creation_hair_color: "Cor do Cabelo",
    character_creation_eye_color: "Cor dos Olhos",
    character_creation_regenerate: "Gerar Retrato Novamente",
    character_creation_generating: "Gerando...",
    character_creation_cooldown: "Aguardando...",
    character_creation_begin_journey: "Iniciar Jornada",
    character_creation_error: "Falha ao gerar o retrato. Por favor, tente novamente.",
    character_creation_error_generic: "Ocorreu um erro ao gerar o retrato.",
    
    library_title: "Biblioteca de Jornadas",
    library_back_to_menu: "Voltar ao Menu",
    library_no_journeys: "Sua biblioteca está vazia. Complete uma jornada para salvá-la aqui.",
    library_journey_date: "Data",
    library_journey_world: "Mundo",
    library_journey_turns: "Turnos",
    library_journey_difficulty: "Dificuldade",
    library_view_button: "Ver",
    library_delete_button: "Excluir",
    library_export_button: "Exportar para Arquivo",
    library_delete_confirm: "Tem certeza de que deseja excluir esta jornada para sempre?",
    library_final_outcome: "Resultado Final",
    library_character: "Personagem",
    library_story_log: "Registro da História",
    library_save_journey: "Salvar Jornada na Biblioteca",
    library_journey_saved: "Jornada Salva!",
  },
};

export const languageNames: Record<Language, string> = {
    en: "English",
    pt: "Português",
};